set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_TOOLCHAIN_PREFIX i686-elf)

set(CMAKE_ASM-ATT-COMPILER as)

include(CMakeForceCompiler)
set(CMAKE_C_COMPILER ${CMAKE_TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_TOOLCHAIN_PREFIX}-g++)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS "-ffreestanding")
set(CMAKE_C_FLAGS_DEBUG "-ggdb -W -Wall -Wextra -Winline")

set(LINKER_SCRIPT ${CMAKE_SOURCE_DIR}/toolchain/x86/linker.ld)
set(CMAKE_EXE_LINKER_FLAGS "-ffreestanding -nostdlib -T${LINKER_SCRIPT}")

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SOURCE_DIR})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(ZenithOS_ARCH x86)
